import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // PaperIQ Design System Tokens (from Stitch)
        'primary':                    '#ffb690',
        'primary-container':          '#f97316',
        'on-primary':                 '#552100',
        'on-primary-container':       '#ffffff',
        'on-primary-fixed-variant':   '#783200',
        'primary-fixed':              '#ffdbca',
        'primary-fixed-dim':          '#ffb690',
        'on-primary-fixed':           '#341100',
        'background':                 '#07070d',
        'surface':                    '#121414',
        'surface-dim':                '#121414',
        'surface-bright':             '#37393a',
        'surface-container-lowest':   '#0c0f0f',
        'surface-container-low':      '#1a1c1c',
        'surface-container':          '#1e2020',
        'surface-container-high':     '#282a2b',
        'surface-container-highest':  '#333535',
        'on-surface':                 '#e2e2e2',
        'on-surface-variant':         '#e0c0b1',
        'on-background':              '#e2e2e2',
        'surface-tint':               '#ffb690',
        'outline':                    '#a78b7d',
        'outline-variant':            '#584237',
        'surface-variant':            '#333535',
        'inverse-surface':            '#e2e2e2',
        'inverse-on-surface':         '#2f3131',
        'inverse-primary':            '#9d4300',
        'secondary':                  '#c8c6c5',
        'secondary-container':        '#4a4949',
        'secondary-fixed':            '#e5e2e1',
        'secondary-fixed-dim':        '#c8c6c5',
        'on-secondary':               '#313030',
        'on-secondary-container':     '#bab8b7',
        'on-secondary-fixed':         '#1c1b1b',
        'on-secondary-fixed-variant': '#474646',
        'tertiary':                   '#c8c5cf',
        'tertiary-container':         '#9b99a2',
        'tertiary-fixed':             '#e4e1eb',
        'tertiary-fixed-dim':         '#c8c5cf',
        'on-tertiary':                '#303037',
        'on-tertiary-container':      '#323139',
        'on-tertiary-fixed':          '#1b1b22',
        'on-tertiary-fixed-variant':  '#47464e',
        'error':                      '#ffb4ab',
        'error-container':            '#93000a',
        'on-error':                   '#690005',
        'on-error-container':         '#ffdad6',
        'success':                    '#10b981',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '16px',
        '3xl':   '24px',
        full:    '9999px',
      },
      spacing: {
        xs:      '4px',
        sm:      '8px',
        md:      '12px',
        base:    '16px',
        lg:      '24px',
        xl:      '32px',
        xxl:     '48px',
        huge:    '64px',
        section: '96px',
      },
      fontFamily: {
        headline:   ['Space Grotesk', 'sans-serif'],
        body:       ['Geist', 'sans-serif'],
        mono:       ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Space Grotesk'],
        'headline-md': ['Space Grotesk'],
        'body-lg':     ['Geist'],
        'body-md':     ['Geist'],
        'body-sm':     ['Geist'],
        'data-value':  ['JetBrains Mono'],
        'data-label':  ['JetBrains Mono'],
      },
      fontSize: {
        'display-hero':        ['56px', { lineHeight: '1.1',  letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-hero-mobile': ['36px', { lineHeight: '1.2',  fontWeight: '700' }],
        'headline-lg':         ['32px', { lineHeight: '1.3',  letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md':         ['24px', { lineHeight: '1.4',  fontWeight: '600' }],
        'body-lg':             ['18px', { lineHeight: '1.6',  fontWeight: '400' }],
        'body-md':             ['15px', { lineHeight: '1.5',  fontWeight: '400' }],
        'body-sm':             ['13px', { lineHeight: '1.5',  fontWeight: '400' }],
        'data-value':          ['14px', { lineHeight: '1.4',  fontWeight: '500' }],
        'data-label':          ['12px', { lineHeight: '1',    letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}

export default config
